# With this file, another toolchain to the currently selected one will be used, when you execute `cargo build`.
# https://rust-lang.github.io/rustup/overrides.html

[toolchain]
# equals to Rust nightly 1.59
channel = "nightly-2021-12-21"
profile = "minimal"
